# Run when commits are pushed to main branch
trigger:
  branches:
    include:
    - main

# Azure Pipelines workflow to deploy to Azure using azd
# To configure required secrets for connecting to Azure, run `azd pipeline config --provider azdo`

pool:
  vmImage: ubuntu-latest

variables:
# `env_name` is used in deployment jobs to target the correct environment - this default value will get overridden below based on the source branch
- name: 'env_name'
  value: 'unknown'

# The "production" environment is targeted when the source branch is `main`
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
  - group: production
  - name: 'env_name'
    value: 'production'

jobs:
- job: init
  steps:
  - pwsh: |
      Write-Output "environment is set to '$(env_name)'"
    displayName: Show environment

- deployment: deploy
  dependsOn: init
  condition: ne(variables['env_name'], 'unknown')
  environment: '$(env_name)'
  # Use azd provided container image that has azd, infra, multi-language build tools pre-installed
  container: mcr.microsoft.com/azure-dev-cli-apps:latest
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self

        - pwsh: |
            Write-Output "environment is set to '$(env_name)'"
          displayName: Show environment

        - pwsh: |
            npm run env:init
          displayName: Create .env.local file

        - pwsh: |
            azd config set auth.useAzCliAuth "true"
          displayName: Configure AZD to Use AZ CLI Authentication

        - task: AzureCLI@2
          displayName: Provision Infrastructure
          inputs:
            azureSubscription: azconnection
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              azd provision --no-prompt
          env:
            AZURE_ENV_NAME: $(AZURE_ENV_NAME)
            AZURE_LOCATION: $(AZURE_LOCATION)
            AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)

        - pwsh: |
            npm run env:dv
          displayName: Domain Verification

        - task: AzureCLI@2
          displayName: Deploy Application
          inputs:
            azureSubscription: azconnection
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              azd deploy --no-prompt
          env:
            AZURE_ENV_NAME: $(AZURE_ENV_NAME)
            AZURE_LOCATION: $(AZURE_LOCATION)
            AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
